{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On this lab we will put to practice some of the concepts we have learned on this past few days.\n",
    "\n",
    "`NOTE: On this lab you should try to write all the functions yourself using only the most basic of python syntax and without functions such as len, count, sum, max, min, in, etc. Give it a try. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "The cell after each exercise contains a few tests to check if your function works as expected."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Write a function that returns the greater of two numbers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 113,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "8"
      ]
     },
     "execution_count": 113,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def greater(a,b):\n",
    "    \n",
    "    if a > b:\n",
    "        return a\n",
    "        \n",
    "    elif a < b:\n",
    "        return b\n",
    "    \n",
    "greater(5,8)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.223s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Now write a function that returns the largest element on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 116,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (<ipython-input-116-6105f323cf0d>, line 13)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-116-6105f323cf0d>\"\u001b[1;36m, line \u001b[1;32m13\u001b[0m\n\u001b[1;33m    y = WHAT!\u001b[0m\n\u001b[1;37m            ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "arr = [1,28,95,26,2,984,4457,3,68,249,3567,82]\n",
    "\n",
    "print(arr[0])\n",
    "\n",
    "x = 0\n",
    "\n",
    "y = 0\n",
    "\n",
    "for i in arr:\n",
    "        \n",
    "    x = i\n",
    "    \n",
    "    y = WHAT! \n",
    "    \n",
    "    if x > y:\n",
    "        print(x)\n",
    "    \n",
    "    elif x < y:\n",
    "        print(y)\n",
    "        \n",
    "\n",
    "        \n",
    "\n",
    "print(x)\n",
    "    \n",
    "print(y)\n",
    "\n",
    "print(max(arr))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 114,
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block (<ipython-input-114-6346e98f88a4>, line 4)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  File \u001b[1;32m\"<ipython-input-114-6346e98f88a4>\"\u001b[1;36m, line \u001b[1;32m4\u001b[0m\n\u001b[1;33m    greatest(y)\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mIndentationError\u001b[0m\u001b[1;31m:\u001b[0m expected an indented block\n"
     ]
    }
   ],
   "source": [
    "def greatest(arr):\n",
    "\n",
    "    \n",
    "greatest(y)   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 115,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greatest.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 32, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"<ipython-input-6-77b638ed2db0>\", line 9, in greatest\n",
      "    if len(i[0]) > len(i[1]):\n",
      "TypeError: 'int' object is not subscriptable\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.239s\n",
      "\n",
      "FAILED (errors=100)\n"
     ]
    }
   ],
   "source": [
    "# This will testour function \n",
    "test_greatest(greatest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Write a function that sums all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_all(arr):\n",
    "    \n",
    "    x = 0\n",
    "\n",
    "    for i in arr:\n",
    "        \n",
    "        x = x + i\n",
    "    \n",
    "\n",
    "    return(x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.234s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Write another function that multiplies all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mult_all(arr):\n",
    "    \n",
    "    y = 1\n",
    "\n",
    "    for i in arr:\n",
    "    \n",
    "        y = y * i\n",
    "        \n",
    "    return(y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.145s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Now combine those two ideas and write a function that receives a list and either \"+\" or \"*\" and outputs acordingly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5. Ahora combine esas dos ideas y escriba una función que reciba una lista y un \"+\" o \"*\" \n",
    "# y genere los resultados correspondientes\n",
    "\n",
    "def oper_all(arr, oper):\n",
    "    \n",
    "    if arr == \"+\":\n",
    "    \n",
    "        x = 0\n",
    "\n",
    "        for i in arr:\n",
    "\n",
    "            x = x + i\n",
    "\n",
    "\n",
    "        return(x)\n",
    "    \n",
    "    \n",
    "    elif oper == \"*\":\n",
    "        \n",
    "        y = 1\n",
    "\n",
    "        for i in arr:\n",
    "    \n",
    "            y = y * i\n",
    "        \n",
    "        return(y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "F.FFF.F.F.F..F.FFFFFF..F...F.FF....FF.....FF.F...FF....FFFFFFF..F..F....F.....FF..F..FFFFFF..F.F.FF.\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -67 : Should be -67\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -62 : Should be -62\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 37 : Should be 37\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -33 : Should be -33\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 24 : Should be 24\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -27 : Should be -27\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 14 : Should be 14\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 24 : Should be 24\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 11 : Should be 11\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -44 : Should be -44\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -49 : Should be -49\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -70 : Should be -70\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -42 : Should be -42\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -54 : Should be -54\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 23 : Should be 23\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -72 : Should be -72\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -26 : Should be -26\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 25 : Should be 25\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -14 : Should be -14\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 5 : Should be 5\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 5 : Should be 5\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 13 : Should be 13\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 15 : Should be 15\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -51 : Should be -51\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 48 : Should be 48\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 82 : Should be 82\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -27 : Should be -27\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 12 : Should be 12\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 34 : Should be 34\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -2 : Should be -2\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -34 : Should be -34\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 41 : Should be 41\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 20 : Should be 20\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -72 : Should be -72\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 88 : Should be 88\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 6 : Should be 6\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -16 : Should be -16\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -9 : Should be -9\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 2 : Should be 2\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -40 : Should be -40\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -10 : Should be -10\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -191 : Should be -191\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -11 : Should be -11\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -17 : Should be -17\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -3 : Should be -3\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 22 : Should be 22\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 22 : Should be 22\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -21 : Should be -21\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.174s\n",
      "\n",
      "FAILED (failures=48)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Write a function that returns the factorial of a number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 117,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "120\n"
     ]
    }
   ],
   "source": [
    "# Hay que multiplicar todos los números enteros positivos que hay entre ese número y el 1.\n",
    "\n",
    "def factorial(n):\n",
    "\n",
    "    if n == 0:\n",
    "        return 1\n",
    "    else:\n",
    "        return n * factorial(n-1)\n",
    "    \n",
    "print(factorial(n))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.136s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Write a function that takes a list and returns a list of the unique values.\n",
    "\n",
    "`NOTE: You cannot use set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 132,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1, 28, 95, 26, 2, 984, 4457, 3, 68, 249, 3567, 82]\n"
     ]
    }
   ],
   "source": [
    "# 7. Escriba una función que tome una lista y devuelva una lista de valores únicos.\n",
    "\n",
    "arr = [1,28,95,26,2,984,2,4457,3,28,68,249,3567,82]\n",
    "\n",
    "x = []\n",
    "    \n",
    "for i in arr:\n",
    "        \n",
    "    if i not in x:\n",
    "        x.append(i)\n",
    "\n",
    "\n",
    "print(x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "metadata": {},
   "outputs": [],
   "source": [
    "def unique(arr):\n",
    "\n",
    "    x = []\n",
    "    \n",
    "    for i in arr:\n",
    "        \n",
    "        if i not in x:\n",
    "            x.append(i)\n",
    "    \n",
    "    return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 124,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.427s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Write a function that returns the mode of a list, i.e.: the element that appears the most times.\n",
    "`NOTE: You should not use count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 139,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1\n",
      "28\n",
      "95\n",
      "26\n",
      "2\n",
      "984\n",
      "2\n",
      "4457\n",
      "3\n",
      "28\n",
      "68\n",
      "249\n",
      "2\n",
      "3567\n",
      "82\n"
     ]
    }
   ],
   "source": [
    "# 8. Escribe una función que devuelva la moda de una lista, es decir, el elemento que aparece más veces.\n",
    "\n",
    "arr = [1,28,95,26,2,984,2,4457,3,28,68,249,2,3567,82]\n",
    "\n",
    "arr2 = arr\n",
    "\n",
    "y = 0\n",
    "\n",
    "for i in arr:\n",
    "    \n",
    "    if i in arr2:\n",
    "        print(i)\n",
    "\n",
    "# un elemento que aparezca dos veces\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mode_counter(arr):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Write a function that calculates the standard deviation of a list.\n",
    "`NOTE: Do not use any libraries or already built functions. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 142,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.0\n",
      "5.291502622129181\n",
      "9.746794344808963\n",
      "5.0990195135927845\n",
      "1.4142135623730951\n",
      "31.368774282716245\n",
      "1.4142135623730951\n",
      "66.76076692189807\n",
      "1.7320508075688772\n",
      "5.291502622129181\n",
      "8.246211251235321\n",
      "15.7797338380595\n",
      "1.4142135623730951\n",
      "59.724366886556446\n",
      "9.055385138137417\n"
     ]
    }
   ],
   "source": [
    "arr = [1,28,95,26,2,984,2,4457,3,28,68,249,2,3567,82]\n",
    "\n",
    "\n",
    "\n",
    "for i in arr:\n",
    "        \n",
    "        x = i ** 0.5\n",
    "        \n",
    "        print(x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 143,
   "metadata": {},
   "outputs": [],
   "source": [
    "def st_dev(arr):\n",
    "    \n",
    "    for i in arr:\n",
    "        \n",
    "        x = i ** 0.5\n",
    "        \n",
    "    return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 144,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.1698422122999943e-15+19.1049731745428j) != 590.4689920097672 within 5 delta (590.7779875088701 difference) : Should be 590.4689920097672\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.2246467991473532e-16+2j) != 550.3575940173052 within 5 delta (550.3612280062223 difference) : Should be 550.3575940173052\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 5.5677643628300215 != 574.1259000885976 within 5 delta (568.5581357257676 difference) : Should be 574.1259000885976\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 31.448370387032774 != 551.9741549552937 within 5 delta (520.5257845682609 difference) : Should be 551.9741549552937\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.8942479457606638e-15+30.93541659651604j) != 592.3652974858045 within 5 delta (593.1725260541368 difference) : Should be 592.3652974858045\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 14.422205101855956 != 616.8193420656235 within 5 delta (602.3971369637675 difference) : Should be 616.8193420656235\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.7145055188062944e-15+28j) != 585.7832324201636 within 5 delta (586.4520401402108 difference) : Should be 585.7832324201636\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.667949158948721e-15+27.23967694375247j) != 554.3855475071568 within 5 delta (555.0543534509121 difference) : Should be 554.3855475071568\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.4810127218032148e-15+24.186773244895647j) != 578.545916741081 within 5 delta (579.0512738763103 difference) : Should be 578.545916741081\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.7925499530983872e-15+29.274562336608895j) != 565.7767714147195 within 5 delta (566.5336310162564 difference) : Should be 565.7767714147195\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 30.528675044947494 != 586.7803659762471 within 5 delta (556.2516909312997 difference) : Should be 586.7803659762471\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.777848064925646e-15+29.03446228191595j) != 623.5039788487413 within 5 delta (624.1796309078114 difference) : Should be 623.5039788487413\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 16.881943016134134 != 520.5563973307142 within 5 delta (503.67445431458003 difference) : Should be 520.5563973307142\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 26.832815729997478 != 567.0088277555193 within 5 delta (540.1760120255218 difference) : Should be 567.0088277555193\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.1666327625973976e-15+19.05255888325765j) != 558.17712728699 within 5 delta (558.5021982287595 difference) : Should be 558.17712728699\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 23.366642891095847 != 557.9294415554587 within 5 delta (534.5627986643628 difference) : Should be 557.9294415554587\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.8922675500851314e-15+30.903074280724887j) != 597.1592890228159 within 5 delta (597.9583735229694 difference) : Should be 597.1592890228159\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 22.44994432064365 != 570.0030496994439 within 5 delta (547.5531053788002 difference) : Should be 570.0030496994439\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (8.506668532006794e-16+13.892443989449804j) != 545.7188570527708 within 5 delta (545.8956593919597 difference) : Should be 545.7188570527708\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 20.71231517720798 != 665.0855112832038 within 5 delta (644.3731961059958 difference) : Should be 665.0855112832038\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.545434390030521e-15+25.238858928247925j) != 523.2978092622626 within 5 delta (523.9060957640056 difference) : Should be 523.2978092622626\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 16.73320053068151 != 601.9332298409959 within 5 delta (585.2000293103143 difference) : Should be 601.9332298409959\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (3.7246178313515847e-16+6.082762530298219j) != 539.8624343466103 within 5 delta (539.8967012481629 difference) : Should be 539.8624343466103\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.3922785350246735e-15+22.737634001804146j) != 587.1370783685703 within 5 delta (587.5771853936984 difference) : Should be 587.1370783685703\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 31.11269837220809 != 590.6877956413348 within 5 delta (559.5750972691267 difference) : Should be 590.6877956413348\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 29.24038303442689 != 590.6278628927433 within 5 delta (561.3874798583164 difference) : Should be 590.6278628927433\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 16.73320053068151 != 574.4678070000626 within 5 delta (557.7346064693811 difference) : Should be 574.4678070000626\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.7608956103793862e-15+28.75760768909681j) != 549.1485178677495 within 5 delta (549.900986247839 difference) : Should be 549.1485178677495\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.8833299992288378e-15+30.757112998459398j) != 610.5571448881038 within 5 delta (611.3313562822646 difference) : Should be 610.5571448881038\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.5575177201096477e-15+25.436194683953808j) != 606.256457156517 within 5 delta (606.7898250992445 difference) : Should be 606.256457156517\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (4.10759023698152e-16+6.708203932499369j) != 615.5115320518332 within 5 delta (615.5480859273262 difference) : Should be 615.5115320518332\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 31.080540535840107 != 601.5960438699709 within 5 delta (570.5155033341308 difference) : Should be 601.5960438699709\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 31.591137997862628 != 587.8400152629148 within 5 delta (556.2488772650522 difference) : Should be 587.8400152629148\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.6555394899592535e-15+27.03701166919155j) != 601.1996027508084 within 5 delta (601.8072468388277 difference) : Should be 601.1996027508084\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 19.467922333931785 != 575.6051911780427 within 5 delta (556.1372688441108 difference) : Should be 575.6051911780427\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.8542381998417323e-15+30.28200785945344j) != 587.70474946951 within 5 delta (588.4843859857452 difference) : Should be 587.70474946951\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.2578738294074887e-15+20.54263858417414j) != 556.0688853235395 within 5 delta (556.4482053389728 difference) : Should be 556.0688853235395\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 27.820855486487112 != 639.1093411928823 within 5 delta (611.2884857063952 difference) : Should be 639.1093411928823\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 23.40939982143925 != 573.8708198560594 within 5 delta (550.4614200346201 difference) : Should be 573.8708198560594\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (7.960204194457795e-16+13j) != 609.9044779024622 within 5 delta (610.043008455531 difference) : Should be 609.9044779024622\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.681382523495948e-15+27.459060435491963j) != 572.0426349079955 within 5 delta (572.7012974950225 difference) : Should be 572.0426349079955\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.764086604740072e-15+28.809720581775867j) != 556.8237352918387 within 5 delta (557.5685358629518 difference) : Should be 556.8237352918387\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (6.566436914455845e-16+10.723805294763608j) != 573.5916632098972 within 5 delta (573.6918999810754 difference) : Should be 573.5916632098972\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.3046943524524081e-15+21.307275752662516j) != 501.0774755712161 within 5 delta (501.5302947228838 difference) : Should be 501.0774755712161\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (4.10759023698152e-16+6.708203932499369j) != 605.4581028326521 within 5 delta (605.4952636360704 difference) : Should be 605.4581028326521\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.0172680325443644e-15+16.61324772583615j) != 601.3423488773759 within 5 delta (601.5717916868773 difference) : Should be 601.3423488773759\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 26.476404589747453 != 492.13888738424896 within 5 delta (465.6624827945015 difference) : Should be 492.13888738424896\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 8.774964387392123 != 506.7803130689724 within 5 delta (498.0053486815803 difference) : Should be 506.7803130689724\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 31.22498999199199 != 575.6181975044271 within 5 delta (544.3932075124352 difference) : Should be 575.6181975044271\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.7630235816819638e-15+28.792360097775937j) != 612.4094537461831 within 5 delta (613.0859148909706 difference) : Should be 612.4094537461831\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 28.124722220850465 != 493.935630967354 within 5 delta (465.8109087465035 difference) : Should be 493.935630967354\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 26.664583251946766 != 560.7905161493042 within 5 delta (534.1259328973574 difference) : Should be 560.7905161493042\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 17.60681686165901 != 601.4020537939156 within 5 delta (583.7952369322566 difference) : Should be 601.4020537939156\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (9.98669242277009e-16+16.30950643030009j) != 409.6295684314468 within 5 delta (409.9541234496042 difference) : Should be 409.6295684314468\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 21.447610589527216 != 580.9490858798346 within 5 delta (559.5014752903073 difference) : Should be 580.9490858798346\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.1520796012670929e-15+18.81488772222678j) != 527.0050957701851 within 5 delta (527.3408489466201 difference) : Should be 527.0050957701851\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.057034076121997e-15+17.26267650163207j) != 562.1345395560536 within 5 delta (562.399538194953 difference) : Should be 562.1345395560536\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.868339073654853e-15+30.512292604784715j) != 588.317183350196 within 5 delta (589.107891837402 difference) : Should be 588.317183350196\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.841047829040788e-15+30.066592756745816j) != 617.1437715659202 within 5 delta (617.8757438050217 difference) : Should be 617.1437715659202\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 18.466185312619388 != 565.5415721217847 within 5 delta (547.0753868091654 difference) : Should be 565.5415721217847\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.1682385895964447e-15+19.078784028338912j) != 654.4552518112881 within 5 delta (654.7332866315692 difference) : Should be 654.4552518112881\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (5.086340162721822e-16+8.306623862918075j) != 588.523066667739 within 5 delta (588.5816850701353 difference) : Should be 588.523066667739\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 7.615773105863909 != 618.1711883486691 within 5 delta (610.5554152428052 difference) : Should be 618.1711883486691\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.7046362013366222e-15+27.83882181415011j) != 567.7680184082868 within 5 delta (568.4501057500761 difference) : Should be 567.7680184082868\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 28.930952282978865 != 559.6997935179426 within 5 delta (530.7688412349637 difference) : Should be 559.6997935179426\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (4.372863733177457e-16+7.14142842854285j) != 528.175503632422 within 5 delta (528.2237808328612 difference) : Should be 528.175503632422\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 12.609520212918492 != 563.0575352410431 within 5 delta (550.4480150281246 difference) : Should be 563.0575352410431\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.0227817208019735e-15+16.703293088490067j) != 622.8701747117568 within 5 delta (623.0940976653964 difference) : Should be 622.8701747117568\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (6.123233995736766e-16+10j) != 581.4785673817431 within 5 delta (581.5645487169282 difference) : Should be 581.4785673817431\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 5.830951894845301 != 613.6859969875072 within 5 delta (607.855045092662 difference) : Should be 613.6859969875072\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 22.627416997969522 != 571.5681455209228 within 5 delta (548.9407285229533 difference) : Should be 571.5681455209228\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.7427029465431744e-15+28.460498941515414j) != 608.1929415223816 within 5 delta (608.8584844753723 difference) : Should be 608.1929415223816\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 22.090722034374522 != 541.7137444743128 within 5 delta (519.6230224399383 difference) : Should be 541.7137444743128\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 23.2379000772445 != 544.460266288386 within 5 delta (521.2223662111415 difference) : Should be 544.460266288386\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.6061092198783976e-15+26.229754097208j) != 643.9466478562376 within 5 delta (644.4806322033932 difference) : Should be 643.9466478562376\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 26.019223662515376 != 564.6567409480841 within 5 delta (538.6375172855687 difference) : Should be 564.6567409480841\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (8.637884531957314e-16+14.106735979665885j) != 428.2539447296085 within 5 delta (428.4862205211162 difference) : Should be 428.2539447296085\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (3.8726732145403874e-16+6.324555320336759j) != 579.6324500221189 within 5 delta (579.6669536196143 difference) : Should be 579.6324500221189\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 19.8997487421324 != 578.4850595699584 within 5 delta (558.585310827826 difference) : Should be 578.4850595699584\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (2.7383934913210134e-16+4.47213595499958j) != 643.2947808860315 within 5 delta (643.310325671217 difference) : Should be 643.2947808860315\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.0902108180345316e-15+17.804493814764857j) != 523.1688359102727 within 5 delta (523.4717097109545 difference) : Should be 523.1688359102727\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 17.4928556845359 != 569.744019379798 within 5 delta (552.2511636952621 difference) : Should be 569.744019379798\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 26.13426869074396 != 532.6326244642532 within 5 delta (506.4983557735093 difference) : Should be 532.6326244642532\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 28.687976575562104 != 556.3999654196497 within 5 delta (527.7119888440876 difference) : Should be 556.3999654196497\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 27.712812921102035 != 544.9917086525262 within 5 delta (517.2788957314242 difference) : Should be 544.9917086525262\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (7.16706164032155e-16+11.704699910719626j) != 576.1955601437863 within 5 delta (576.3144311306213 difference) : Should be 576.1955601437863\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 23.452078799117146 != 575.6239970591377 within 5 delta (552.1719182600204 difference) : Should be 575.6239970591377\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 20.074859899884732 != 566.3522866275954 within 5 delta (546.2774267277107 difference) : Should be 566.3522866275954\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 13.152946437965905 != 581.624073177856 within 5 delta (568.4711267398901 difference) : Should be 581.624073177856\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.4848053342148696e-15+24.24871130596428j) != 535.1315279931208 within 5 delta (535.6806439029249 difference) : Should be 535.1315279931208\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.7308293289250274e-15+28.26658805020514j) != 627.5979117598704 within 5 delta (628.2341433298178 difference) : Should be 627.5979117598704\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 23.790754506740637 != 587.4637858937443 within 5 delta (563.6730313870037 difference) : Should be 587.4637858937443\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 28.583211855912904 != 608.3360909029283 within 5 delta (579.7528790470154 difference) : Should be 608.3360909029283\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 27.055498516937366 != 589.4756401990093 within 5 delta (562.4201416820719 difference) : Should be 589.4756401990093\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 28.844410203711913 != 561.11372563123 within 5 delta (532.269315427518 difference) : Should be 561.11372563123\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.1952075940962807e-15+19.519221295943137j) != 531.6181882716822 within 5 delta (531.9764074667839 difference) : Should be 531.6181882716822\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 24.145392935299274 != 453.2307058521882 within 5 delta (429.0853129168889 difference) : Should be 453.2307058521882\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.924683522861561e-15+31.432467291003423j) != 523.6028806898094 within 5 delta (524.5454953258742 difference) : Should be 523.6028806898094\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.3373344910022568e-15+21.840329667841555j) != 508.3255431020299 within 5 delta (508.7945142884047 difference) : Should be 508.3255431020299\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\arroy\\datamad1020\\module-1\\lab-functions\\mod\\testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: (1.5551085651948053e-15+25.39685019840059j) != 535.3312642654079 within 5 delta (535.933356397976 difference) : Should be 535.3312642654079\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.260s\n",
      "\n",
      "FAILED (failures=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Write a function to check if a string is a pangram, i.e.: if it contains all the letters of the alphabet at least once."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def pangram(string):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Write a function that receives a string of comma separated words and returns a string of comma separated words sorted alphabetically.\n",
    "\n",
    "`NOTE: You may use sorted but not split and definitely no join! 🤪`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sort_alpha(string):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Write a function to check if a given password is strong (at least 8 characters, at least one lower case, at least one upper case, at least one number and at least one special character). It should output True if strong and False if not.\n",
    "`Valid special characters: # @ ! $ % & ( ) ^ * [ ] { }`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(string):\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# This will test your function \n",
    "test_pass(check_pass)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
